# Generated by Django 5.1 on 2024-10-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('SU', 'Supporter'), ('BM', 'Band member')], max_length=2),
        ),
    ]
