# Generated by Django 5.1 on 2024-10-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_user_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='users_bands',
        ),
    ]
